export const ASSET = {
	bg1: {
		layer1: "./res/bg1/layer-1.png",
		layer2: "./res/bg1/layer-2.png",
		layer3: "./res/bg1/layer-3.png",
		layer4: "./res/bg1/layer-4.png",
		layer5: "./res/bg1/layer-5.png",
	},
	bg2: {
		layer1: "./res/bg2/layer-1.png",
		layer2: "./res/bg2/layer-2.png",
		layer3: "./res/bg2/layer-3.png",
		layer4: "./res/bg2/layer-4.png",
		layer5: "./res/bg2/layer-5.png",
	},
	ctl: {
		action: "./res/ctl/action.svg",
		down: "./res/ctl/down.svg",
		full_screen: "./res/ctl/full_screen.svg",
		icon: "./res/ctl/icon.svg",
		info: "./res/ctl/info.svg",
		left: "./res/ctl/left.svg",
		life_icon_inactive: "./res/ctl/life_icon_inactive.svg",
		life_icon: "./res/ctl/life_icon.svg",
		normal_screen: "./res/ctl/normal_screen.svg",
		pause: "./res/ctl/pause.svg",
		power_icon_inactive: "./res/ctl/power_icon_inactive.svg",
		power_icon: "./res/ctl/power_icon.svg",
		power1: "./res/ctl/power1.svg",
		power2: "./res/ctl/power2.svg",
		right: "./res/ctl/right.svg",
		shield_icon_inactive: "./res/ctl/shield_icon_inactive.svg",
		shield_icon: "./res/ctl/shield_icon.svg",
		start: "./res/ctl/start.svg",
		stopwatch_icon_inactive: "./res/ctl/stopwatch_icon_inactive.svg",
		stopwatch_icon: "./res/ctl/stopwatch_icon.svg",
		up: "./res/ctl/up.svg",
	},
	enemy: {
		enemy1: "./res/enemy/enemy1.png",
		enemy2: "./res/enemy/enemy2.png",
		enemy3: "./res/enemy/enemy3.png",
		enemy4: "./res/enemy/enemy4.png",
		enemy5: "./res/enemy/enemy5.png",
		enemy6: "./res/enemy/enemy6.png",
		enemy7: "./res/enemy/enemy7.png",
		enemy8: "./res/enemy/enemy8.png",
		enemy9: "./res/enemy/enemy9.png",
		enemy10: "./res/enemy/enemy10.png",
		enemy11: "./res/enemy/enemy11.png",
	},
	font: {
		Creepster_eot: "./res/font/Creepster.eot",
		Creepster_svg: "./res/font/Creepster.svg",
		Creepster_ttf: "./res/font/Creepster.ttf",
		Creepster_woff: "./res/font/Creepster.woff",
		Creepster_woff2: "./res/font/Creepster.woff2",
	},
	boom: "./res/boom.png",
	boom_wav: "./res/boom.wav",
	fire: "./res/fire.png",
	player: "./res/player.png",
};
